### ISSUE TITLE
Exception thrown when project sourceCompatibility=1.8

### ISSUE THREAD

**Issue by Yeriwyn** [junkdog/ecs-matrix#7]
When running against sources compiled against language level 1.8, fails with the following (can reproduce using DaanVanYperen/libgdx-artemis-quickstart, just change the sourceCompatiblity to 1.8 in core/build.gradle)

```
:matrix:generateMatrix
Exception in thread "main" java.lang.IllegalArgumentException
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at net.onedaybeard.ecs.model.scan.ConfigurationResolver.findExtendedArtemisTypes(ConfigurationResolver.java:116)
    at net.onedaybeard.ecs.model.scan.ConfigurationResolver.findExtendedArtemisTypes(ConfigurationResolver.java:132)
    at net.onedaybeard.ecs.model.scan.ConfigurationResolver.<init>(ConfigurationResolver.java:61)
    at net.onedaybeard.ecs.model.EcsTypeInspector.<init>(EcsTypeInspector.java:23)
    at net.onedaybeard.ecs.model.ComponentDependencyMatrix.detectAndProcess(ComponentDependencyMatrix.java:35)
    at com.artemis.cli.MatrixCommand.execute(MatrixCommand.java:45)
    at com.artemis.cli.CliApplication.parse(CliApplication.java:23)
    at com.artemis.cli.CliApplication.main(CliApplication.java:11)
:matrix:generateMatrix FAILED
```

**Comment by junkdog** [comment]
Thanks for reporting. I'll need to update ASM to version 5; the current version doesn't support java 8 bytecode.

**Comment by junkdog** [comment]
0.1.2 contains the fix.
